set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on
set -g status-keys vi
setw -g mode-keys vi
set -sg escape-time 0
set -g set-clipboard on
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
