color_theme = "TTY"
theme_background = False
truecolor = True
force_tty = False
show_gpu_info = Auto
update_ms = 1500
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = True
proc_colors = True
proc_gradient = True
proc_per_core = True
proc_mem_bytes = True
check_temp = True
show_coretemp = True
disks_filter = "exclude=/boot"
net_download = 100M
net_upload = 100M
cpu_sensor = "Auto"
show_battery = True
clock_format = "%H:%M"
